# --- File: C:\Hostel-Main\app\models\hostel\hostel_comparison.py ---
"""
Hostel comparison model for competitive analysis.
"""

from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    CheckConstraint,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base.base_model import TimestampModel
from app.models.base.mixins import UUIDMixin

if TYPE_CHECKING:
    from app.models.hostel.hostel import Hostel


class HostelComparison(TimestampModel, UUIDMixin):
    """
    Hostel comparison data for competitive analysis.
    
    Stores comparison metrics between hostels for benchmarking
    and competitive intelligence.
    """

    __tablename__ = "hostel_comparisons"

    # Primary Hostel
    hostel_id: Mapped[UUID] = mapped_column(
        ForeignKey("hostels.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Primary hostel being compared",
    )

    # Comparison Set
    comparison_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        comment="Name/title of this comparison",
    )
    comparison_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="Type of comparison (competitive, regional, category)",
    )
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Description of comparison criteria",
    )

    # Compared Hostels (stored as JSON array of hostel IDs)
    compared_hostel_ids: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Array of hostel IDs being compared",
    )

    # Comparison Metrics (stored as structured JSON)
    metrics: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Detailed comparison metrics",
    )

    # Price Comparison
    price_ranking: Mapped[Optional[int]] = mapped_column(
        nullable=True,
        comment="Price ranking (1 = cheapest)",
    )
    price_percentile: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Price percentile in comparison set",
    )

    # Rating Comparison
    rating_ranking: Mapped[Optional[int]] = mapped_column(
        nullable=True,
        comment="Rating ranking (1 = highest rated)",
    )
    rating_percentile: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Rating percentile in comparison set",
    )

    # Occupancy Comparison
    occupancy_ranking: Mapped[Optional[int]] = mapped_column(
        nullable=True,
        comment="Occupancy ranking (1 = highest occupancy)",
    )
    occupancy_percentile: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Occupancy percentile in comparison set",
    )

    # Overall Performance
    overall_ranking: Mapped[Optional[int]] = mapped_column(
        nullable=True,
        comment="Overall ranking in comparison set",
    )
    performance_score: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Overall performance score (0-100)",
    )

    # Competitive Position
    competitive_advantages: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Identified competitive advantages",
    )
    competitive_disadvantages: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Identified competitive disadvantages",
    )

    # Recommendations
    recommendations: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="AI-generated recommendations",
    )

    # Validity
    valid_from: Mapped[datetime] = mapped_column(
        nullable=False,
        default=datetime.utcnow,
        comment="Comparison valid from",
    )
    valid_until: Mapped[Optional[datetime]] = mapped_column(
        nullable=True,
        comment="Comparison valid until",
    )
    is_active: Mapped[bool] = mapped_column(
        nullable=False,
        default=True,
        index=True,
        comment="Is this comparison currently active",
    )

    # Metadata
    generated_by: Mapped[Optional[str]] = mapped_column(
        String(20),
        nullable=True,
        comment="Generated by (system/admin/user)",
    )
    generated_at: Mapped[datetime] = mapped_column(
        nullable=False,
        default=datetime.utcnow,
        comment="Generation timestamp",
    )

    # Relationships
    hostel: Mapped["Hostel"] = relationship(
        "Hostel",
        foreign_keys=[hostel_id],
    )

    # Table Arguments
    __table_args__ = (
        Index("idx_comparison_hostel_type", "hostel_id", "comparison_type"),
        Index("idx_comparison_active", "is_active"),
        Index("idx_comparison_valid", "valid_from", "valid_until"),
        CheckConstraint(
            "comparison_type IN ('competitive', 'regional', 'category', 'custom')",
            name="check_comparison_type_valid",
        ),
        CheckConstraint(
            "price_percentile IS NULL OR (price_percentile >= 0 AND price_percentile <= 100)",
            name="check_price_percentile_range",
        ),
        CheckConstraint(
            "rating_percentile IS NULL OR (rating_percentile >= 0 AND rating_percentile <= 100)",
            name="check_rating_percentile_range",
        ),
        CheckConstraint(
            "performance_score IS NULL OR (performance_score >= 0 AND performance_score <= 100)",
            name="check_performance_score_range",
        ),
        {"comment": "Hostel comparison and competitive analysis data"},
    )

    def __repr__(self) -> str:
        return (
            f"<HostelComparison(id={self.id}, hostel_id={self.hostel_id}, "
            f"type='{self.comparison_type}')>"
        )

    @property
    def is_valid(self) -> bool:
        """Check if comparison is currently valid."""
        now = datetime.utcnow()
        if not self.is_active:
            return False
        if self.valid_until and now > self.valid_until:
            return False
        return now >= self.valid_from


class BenchmarkData(TimestampModel, UUIDMixin):
    """
    Industry and regional benchmark data.
    
    Stores benchmark metrics for comparison against industry standards.
    """

    __tablename__ = "benchmark_data"

    # Benchmark Identification
    benchmark_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="Benchmark type (industry, regional, category)",
    )
    category: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="Hostel category for this benchmark",
    )
    region: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        index=True,
        comment="Geographic region",
    )

    # Time Period
    period_start: Mapped[datetime] = mapped_column(
        nullable=False,
        comment="Benchmark period start",
    )
    period_end: Mapped[datetime] = mapped_column(
        nullable=False,
        comment="Benchmark period end",
    )

    # Metrics (stored as structured JSON)
    metrics: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Benchmark metrics data",
    )

    # Statistical Data
    sample_size: Mapped[int] = mapped_column(
        nullable=False,
        comment="Number of hostels in sample",
    )
    confidence_level: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="Statistical confidence level",
    )

    # Key Metrics (for quick access)
    avg_occupancy_rate: Mapped[Decimal] = mapped_column(
        Numeric(5, 2),
        nullable=False,
        comment="Average occupancy rate",
    )
    avg_pricing: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        nullable=False,
        comment="Average pricing",
    )
    avg_rating: Mapped[Decimal] = mapped_column(
        Numeric(3, 2),
        nullable=False,
        comment="Average rating",
    )

    # Source
    data_source: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Source of benchmark data",
    )
    verified: Mapped[bool] = mapped_column(
        nullable=False,
        default=False,
        comment="Data verification status",
    )

    # Table Arguments
    __table_args__ = (
        Index("idx_benchmark_type_category", "benchmark_type", "category"),
        Index("idx_benchmark_region", "region"),
        Index("idx_benchmark_period", "period_start", "period_end"),
        CheckConstraint(
            "period_end > period_start",
            name="check_benchmark_period_valid",
        ),
        CheckConstraint(
            "sample_size > 0",
            name="check_sample_size_positive",
        ),
        CheckConstraint(
            "avg_occupancy_rate >= 0 AND avg_occupancy_rate <= 100",
            name="check_avg_occupancy_range",
        ),
        CheckConstraint(
            "avg_rating >= 0 AND avg_rating <= 5",
            name="check_avg_rating_range",
        ),
        UniqueConstraint(
            "benchmark_type",
            "category",
            "region",
            "period_start",
            "period_end",
            name="uq_benchmark_unique",
        ),
        {"comment": "Industry and regional benchmark data"},
    )

    def __repr__(self) -> str:
        return (
            f"<BenchmarkData(id={self.id}, type='{self.benchmark_type}', "
            f"category='{self.category}')>"
        )


class CompetitorAnalysis(TimestampModel, UUIDMixin):
    """
    Detailed competitor analysis tracking.
    
    Monitors specific competitor hostels and tracks their performance.
    """

    __tablename__ = "competitor_analysis"

    # Hostel References
    hostel_id: Mapped[UUID] = mapped_column(
        ForeignKey("hostels.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Our hostel",
    )
    competitor_hostel_id: Mapped[UUID] = mapped_column(
        ForeignKey("hostels.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Competitor hostel",
    )

    # Analysis Period
    analysis_date: Mapped[datetime] = mapped_column(
        nullable=False,
        index=True,
        comment="Date of analysis",
    )

    # Competitor Metrics
    competitor_metrics: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Detailed competitor metrics",
    )

    # Comparison Results
    price_difference: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        nullable=False,
        comment="Price difference (our price - competitor price)",
    )
    rating_difference: Mapped[Decimal] = mapped_column(
        Numeric(3, 2),
        nullable=False,
        comment="Rating difference (our rating - competitor rating)",
    )
    occupancy_difference: Mapped[Decimal] = mapped_column(
        Numeric(5, 2),
        nullable=False,
        comment="Occupancy difference (our % - competitor %)",
    )

    # Strategic Insights
    competitive_threats: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Identified competitive threats",
    )
    opportunities: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Identified opportunities",
    )

    # Actions
    recommended_actions: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Recommended strategic actions",
    )
    action_priority: Mapped[Optional[str]] = mapped_column(
        String(20),
        nullable=True,
        comment="Priority level for actions",
    )

    # Table Arguments
    __table_args__ = (
        Index(
            "idx_competitor_analysis_hostels",
            "hostel_id",
            "competitor_hostel_id",
        ),
        Index("idx_competitor_analysis_date", "analysis_date"),
        CheckConstraint(
            "hostel_id != competitor_hostel_id",
            name="check_different_hostels",
        ),
        CheckConstraint(
            "action_priority IS NULL OR action_priority IN ('low', 'medium', 'high', 'urgent')",
            name="check_action_priority_valid",
        ),
        UniqueConstraint(
            "hostel_id",
            "competitor_hostel_id",
            "analysis_date",
            name="uq_competitor_analysis_date",
        ),
        {"comment": "Detailed competitor analysis and tracking"},
    )

    def __repr__(self) -> str:
        return (
            f"<CompetitorAnalysis(id={self.id}, hostel_id={self.hostel_id}, "
            f"competitor={self.competitor_hostel_id})>"
        )